### ISSUE TITLE
i can'tuse the tool

### ISSUE THREAD

**Issue by korozaki** [Vedant-Bhalgama/VySecator#3]
when i choice the third that tell me
VySec>: Please enter script path --> /home/koro/kage/hi.apk                                                                                                    
Traceback (most recent call last):                                                                                                                             
  File "./VySec.py", line 83, in <module>                                                                                                                      
    ask_user_choice()                                                                                                                                          
  File "./VySec.py", line 73, in ask_user_choice                                                                                                               
    subprocess.call(['wine', '/root/.wine/drive_c/Python27/Scripts/pyarmor.exe', 'pack', '-e', '--onefile --noconsole', ask_path])                             
  File "/usr/lib/python2.7/subprocess.py", line 172, in call                                                                                                   
    return Popen(*popenargs, **kwargs).wait()                                                                                                                  
  File "/usr/lib/python2.7/subprocess.py", line 394, in __init__                                                                                               
    errread, errwrite)                                                                                                                                         
  File "/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child                                                                                        
    raise child_exception                                                                                                                                      
OSError: [Errno 2] No such file or directory

![Capture d’écran_2020-08-06_02-51-33](https://user-images.githubusercontent.com/68153795/89472122-f9ccfa00-d77f-11ea-93ca-9967b8c209be.png)

**Comment by Vedant-Bhalgama** [comment]
Hey There!

Can I know on which OS are you using this? 

Also PLEASE READ THE DOCUMENTATION AS MY TOOL VYSECATOR IS NOT COMPATIBLE WITH MSFVENOM PAYLOADS. I AM WORKING ON A UPDATE IN WHICH U WILL BE ABLE TO COMPILE MSFVENOM PAYLOADS ALSO

**Comment by korozaki** [comment]
Hello,
I use kali linux and okay thank you for answer to me.

Le jeu. 6 août 2020 à 04:22, Vedant Bhalgama <notifications@github.com> a
écrit :

**Comment by Vedant-Bhalgama** [comment]
Ok! 

Also you should read documentation it was clearly written that this is made for python programs only

**Comment by korozaki** [comment]
Thanks for you answer

**Comment by korozaki** [comment]
okay Provenance : Courrier pour Windows 10 De : Vedant BhalgamaEnvoyé le :jeudi 6 août 2020 11:26À : Vedant-Bhalgama/VySecatorCc : korozaki; State changeObjet :Re: [Vedant-Bhalgama/VySecator] i can'tuse the tool (#3) Ok!Also you should read documentation it was clearly written that this is made for python programs only—You are receiving this because you modified the open/close state.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by Vedant-Bhalgama** [comment]
What is this??
